include(${CMAKE_CURRENT_LIST_DIR}/flags.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/utils.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/superbuild_utils.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/target_utils.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/test_utils.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/install_utils.cmake)
